apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbye-task
spec:
  params:
    - name: username
      type: string
      description: The name of the user to say goodbye to
      default: "World"
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/sh
        echo "Goodbye $(params.username)!"
