apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-cleaner-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-cleaner-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["tekton.dev"]
  resources: ["taskruns", "pipelineruns"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-cleaner-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tekton-cleaner-sa
  namespace: default
roleRef:
  kind: Role
  name: tekton-cleaner-role
  apiGroup: rbac.authorization.k8s.io
